name: Android Build & Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Release APK
      run: ./gradlew assembleRelease
    
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SimpleLevelPro-APK
        path: app/build/outputs/apk/release/*.apk
    
    - name: Create GitHub Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/*.apk
        tag_name: v1.0.${{ github.run_number }}
        name: "Release v1.0.${{ github.run_number }}"
        body: |
          ## SimpleLevel Pro v1.0.${{ github.run_number }}
          Download APK und installieren!
        draft: false